
name: "Dashboard: Edit Homelab"
description: "Update the Homelab page"
title: "Dashboard - Homelab"
body:
  - type: markdown
    attributes:
      value: "<!--dashboard:homelab-->
Submit to update the Homelab page."

  - type: textarea
    id: stack
    attributes:
      label: "Stack (Markdown list)"
      placeholder: "- Windows AD + Win11
- Ubuntu
- Wazuh
- Security Onion
- pfSense"

  - type: textarea
    id: design
    attributes:
      label: "Design Snapshot (Markdown)"

  - type: textarea
    id: focus
    attributes:
      label: "Focus Areas (Markdown)"

  - type: textarea
    id: milestones
    attributes:
      label: "Milestones / Mini-Log (Markdown)"
      placeholder: "- Day 1: ...
- Day 2: ..."

  - type: textarea
    id: notes
    attributes:
      label: "Notes / Extra (Markdown)"
