
name: "Dashboard: Edit Contact"
description: "Update the Contact page"
title: "Dashboard - Contact"
body:
  - type: markdown
    attributes:
      value: "<!--dashboard:contact-->
Submit to update the Contact page."

  - type: input
    id: linkedin
    attributes:
      label: "LinkedIn URL"
      placeholder: "https://www.linkedin.com/in/omar-hamed-sec"

  - type: input
    id: github
    attributes:
      label: "GitHub URL"
      placeholder: "https://github.com/omarhamedsec"

  - type: input
    id: email
    attributes:
      label: "Email"
      placeholder: "omarhamed.sec@gmail.com"

  - type: textarea
    id: extras
    attributes:
      label: "Extra Links / Notes (Markdown)"
      placeholder: "CV: /assets/docs/....pdf
Resume: /assets/docs/....pdf"
